# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('imageName', models.CharField(max_length=200)),
                ('imageDescription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='imageLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Photos.Location'),
        ),
    ]
