# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-10-11 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='Imagecategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Photos.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=200),
        ),
    ]
