# Generated by Django 3.1.2 on 2020-10-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0003_auto_20201011_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='Imagecategory',
            new_name='imageCategory',
        ),
    ]
